### PR TITLE
Replacing classes data from hard-coded to firestore

### LINKED ISSUE #4: Adding new Homeworks and Classes under SWoC 2021
The idea of this app looks interesting. But as I can see that the homework and classes are hard coded. So I can work on a method to add new homeworks and classes to this list. I will add beautifully designed pages for adding these. May I go ahead with this under Script Winter of Code 2021. I have ideas of adding various other features also to this app.

### PR DESCRIPTION
**Pull request by nicks101**
# Description

- Dummy data added on firestore : colleges -> USICT-BTECH-CSE-3 -> classes
- Fetching and displaying firestore data (classes) in the app.

TODO : 
- Implement add a class feature : a screen where user can add his/her classes (and homework) -> UI pending

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Friday/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by HimeshNayak — COMMENTED** [review]
Great Work @nicks101 ! 
Now just the classes are to fetched for the college of the user.

**Comment by nicks101** [comment]
> Great Work @nicks101 !
> Now just the classes are to fetched for the college of the user.

That's the issue. We're not storing college document ID in user document. How do a user's selected college?

**Comment by HimeshNayak** [comment]
Hey @nicks101! To resolve this we can add the college reference of the user. I am adding another regarding this. If you want to work on it then I'll assign it to you. After that issue you can continue with this issue.

**Comment by HimeshNayak** [comment]
> > Great Work @nicks101 !
> > Now just the classes are to fetched for the college of the user.
> 
> That's the issue. We're not storing college document ID in user document. How do I access user's selected college?

The collegeRef can be added for fetching the classes and homework. Since there is already an issue about the signup form, we can add it in that issue only. Once that is done, you may resume your work. For now, you can make a field in the user document collegeRef and code accordingly and submit your PR.

**Comment by nicks101** [comment]
> > > Great Work @nicks101 !
> > > Now just the classes are to fetched for the college of the user.
> > 
> > 
> > That's the issue. We're not storing college document ID in user document. How do I access user's selected college?
> 
> The collegeRef can be added for fetching the classes and homework. Since there is already an issue about the signup form, we can add it in that issue only. Once that is done, you may resume your work. For now, you can make a field in the user document collegeRef and code accordingly and submit your PR.

I created the field `collegeID` in the user model. Now classes are fetched for this college ID only (this should be specified during sign-up).

**Review by HimeshNayak — APPROVED** [review]
Great Work @nicks101!
LGTM @avinashkranjan, you may merge this PR

**Review by avinashkranjan — APPROVED** [review]

**Pull request merged**
