### PR TITLE
forgot password feature

### PR DESCRIPTION
**Pull request by namancoder**
I have added the feature , please review it .

### CODE REVIEW

**Comment by avinashkranjan** [comment]
@namancoder Kindly Resolve the conflicts

**Review by HimeshNayak — CHANGES_REQUESTED** [review]
Good Work! @namancoder 

Please implement these changes and send a PR
1. Use TextButton and ElevatedButton instead of FlatButton and RaisedButton respectively.
2. Add a Snackbar / AlertBox telling the user that the email has been sent and login with the new password.
3.  Change the positioning of the send email button.
Screenshot_20210312_225147
Screenshot_20210312_225155

**Comment by namancoder** [comment]
Changes Made.

**Review by HimeshNayak — CHANGES_REQUESTED** [review]
1. login_form.dart still contains FlatButton at line 137. FlatButton is depreciated.
image

2. The "Email Sent Successfully" Snackbar appears even if the email is badly formatted. Add Snackbars according to the errors. 
image

Implement these changes and send the PR.

**Review by HimeshNayak — APPROVED** [review]
Great Work! @namancoder 
I have added error handling if there is no user found in firebase auth.
LGTM @avinashkranjan you can merge this PR.

**Review by avinashkranjan — APPROVED** [review]
LGTM..🚩

**Pull request merged**
