### PR TITLE
Increased the margin for logout button to make it visible

### LINKED ISSUE #84: Bottom Padding of the Logout Button
The Logout button has very less bottom padding, and thus it is not visible to the user even after scrolling.

Increase the padding.

Screenshot_20210313_225436

If anyone wants to work on this under GSSOC21, comment here, I'll assign you.

### PR DESCRIPTION
**Pull request by D-Ajay-Kumar**
# Description

The logout button was not visible even after scrolling because the margin values weren't set correctly.

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Friday/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

Before

After

### CODE REVIEW

**Comment by SamarpanCoder2002** [comment]
> # Description
> The logout button was not visible even after scrolling because the margin values weren't set correctly.
> 
> ## Fixes #84
> ## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Friday/blob/master/CONTRIBUTING.md)?
> * [x]  Yes
> * [ ]  No
> 
> ## Type of change
> * [x]  Bug fix (non-breaking change which fixes an issue)
> * [ ]  New feature (non-breaking change which adds functionality)
> * [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
> 
> ## Checklist:
> * [x]  My code follows the style guidelines(Clean Code) of this project
> * [x]  I have performed a self-review of my own code
> * [x]  My changes generate no new warnings
> * [x]  I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.
> 
> Before
> 
> 
> After
> 

It's really good to fix that bug... I often suffering a lot in that

**Review by HimeshNayak — APPROVED** [review]
LGTM @avinashkranjan you can merge this PR

**Review by avinashkranjan — APPROVED** [review]

**Comment by avinashkranjan** [comment]
@D-Ajay-Kumar Kindly Resolve the Conflicts

**Comment by D-Ajay-Kumar** [comment]
Done. Please check it :)

**Pull request merged**
