### PR TITLE
added color scheme

### LINKED ISSUE #188: Add better color Scheme for UI
please Assign this issue to me under gssoc 23 @avinashkranjan

### PR DESCRIPTION
**Pull request by Abhinavcode13**
# Description

Added new color scheme
## Fixes #188 

closes the issue number #188 

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Friday/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by Abhinavcode13** [comment]
@avinashkranjan please check the PR.

**Review by Abhinavcode13 — COMMENTED** [review]
Added the new color scheme link

**Review by avinashkranjan — CHANGES_REQUESTED** [review]
Convert and write this file in `MARKDOWN`

**Comment by Abhinavcode13** [comment]
@avinashkranjan Please check updated to markdown format thanks

**Review by avinashkranjan — APPROVED** [review]

**Pull request merged**
