### PR TITLE
Added Design Prototype for Website

### LINKED ISSUE #148: Design Prototype for Website
Hey, I would like to create the prototype for the static website which would describe the app.
Please assign me this under GSSoC'21. Thank you :) @HimeshNayak @avinashkranjan

### PR DESCRIPTION
**Pull request by deeptea22**
# Description

Added the Design Prototype for the Website

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Friday/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change
- [x] New feature (non-breaking change which adds functionality)

https://www.figma.com/file/xviuRdqrYnuZGrBBH5Rgrz/Untitled?node-id=29%3A2

### CODE REVIEW

**Comment by deeptea22** [comment]
Hey, @avinashkranjan. Please have a look. Thank you :)

**Comment by avinashkranjan** [comment]
Hey @deeptea22 Kindly Make the Following Changes:

1. Design Look Too Flat, Make it a little Trendy, Adding Shapes or Blobs in the corner..
2. Nav Bar: [Home, Features, Contact Us] --> Right Side 
                  [Friday] --> Left Side
3. Add a Phone, Preferably iPhone and Add the Application Preview carousel on the screen of Iphone. Keep it in right Side
4. Add a Little Description and then a **Download for android** **Download for iOS** Buttons Side by Side..
5. Don't Make Features Section So Long, Add Two Rows of 3 Columns with Line icon Representing the Feature and below that description of the feature.
6. Then Testimonials
7. Contact Us
8. Footer.

**Comment by deeptea22** [comment]
Hey, @avinashkranjan Have done all the changes please have a look : 
https://www.figma.com/file/xviuRdqrYnuZGrBBH5Rgrz/Untitled?node-id=0%3A1

To visualize the carousel :

https://user-images.githubusercontent.com/67323371/115695314-50ff1300-a37f-11eb-986e-d6d88286acc9.mp4

**Comment by avinashkranjan** [comment]
I was talking something like this 
Screenshot 2021-04-23 123912

in Black and Purple Theme..With a Dark Mode slider at the corner. and Horizontal carousel in the phone..

and for the Features section:

Screenshot 2021-04-23 124151


Don't add the Social Icons on the side.

**Comment by deeptea22** [comment]
> I was talking something like this
> Screenshot 2021-04-23 123912
> 
> in Black and Purple Theme..With a Dark Mode slider at the corner. and Horizontal carousel in the phone..
> 
> and for the Features section:
> 
> Screenshot 2021-04-23 124151
> 
> Don't add the Social Icons on the side.

Okay @avinashkranjan , I went by the prototype but if you want me to do it this way, i will do so

**Comment by deeptea22** [comment]
Hey @avinashkranjan How about this, please have a look and let me know 
https://www.figma.com/file/mmPKUPWt8H4sZBEJ9X5U6b/Untitled?node-id=0%3A1

https://user-images.githubusercontent.com/67323371/115890373-8173a980-a472-11eb-8e9c-4a76de7f8f0d.mp4

**Comment by avinashkranjan** [comment]
@deeptea22 LGTM..Just add a Dark/Light Theme Toggle Button in the Nav bar.

**Comment by deeptea22** [comment]
Hey, @avinashkranjan I have added the toggle button in the navbar and have updated the PR. Please take a look. Thank you :)

**Comment by avinashkranjan** [comment]
> Hey, @avinashkranjan I have added the toggle button in the navbar and have updated the PR. Please take a look. Thank you :)

Great Job @deeptea22 , Just a Light Themed Prototype too..As in Just Change the Blacks to White and PR will be ready to Merge

**Review by avinashkranjan — APPROVED** [review]

**Comment by deeptea22** [comment]
Hey, @avinashkranjan I have added the Light Theme as well. Please take a look. Thank you :)

**Review by avinashkranjan — APPROVED** [review]

**Pull request merged**
