### PR TITLE
Added Profile Page and User Addtional Information Form

### LINKED ISSUE #41: Add UserInfo model and collection to the App
In order to display the information in Profile Page, we need to collect the relevant information from the users and need to create a `User` model to hold them and also a `users` collection in Firestore for the same.

Tasks that need to be done:

- [ ] Create a `User` model/class with relevant attributes
- [ ] Create a `users` collection for saving user information
- [ ] Create a Form to be displayed while Onboarding/Signing up to collect the aforementioned information 
- [ ] Fetching information from `users` and displaying them on the Profile page.

I would like to work on this as it is related to the Profile Page, the issue which I'm currently working on.

### PR DESCRIPTION
**Pull request by Imadarshsri**
Following Tasks accomplished:

- [x] Added **Profile Page**
- [x] Added '**users**' collection in Firestore and Integrated with App
- [x] Added an **Additional Information form** 
- [x] Modified Home Page Greeting according to the user info
- [x] Fixes Recent Homeworks Overflow 
- [x] Fixes #41 and #8

### CODE REVIEW

**Comment by avinashkranjan** [comment]
@Imadarshsri Add SS of the Changes..

**Comment by Imadarshsri** [comment]
hey @avinashkranjan, Have a look at this demo...

demo

**Review by avinashkranjan — APPROVED** [review]
Looks Great..🔥🔥

Great Job @Imadarshsri 👏🏻

**Comment by Imadarshsri** [comment]
Thanks...@avinashkranjan

**Pull request merged**
