### PR TITLE
added one logo and one animated logo

### PR DESCRIPTION
**Pull request by kanchi12P**
#56 
Hey @avinashkranjan  I have added two logos in Friday/assets/icons/
Kindly, accept my pull request.

### CODE REVIEW

**Comment by kanchi12P** [comment]
@avinashkranjan please review my pr

**Review by avinashkranjan — CHANGES_REQUESTED** [review]
Do you have any other iterations for the Same. this does look app like icon

**Comment by kanchi12P** [comment]
> Do you have any other iterations for the Same. this does look app like icon
I didn't get it
can you please elaborate on what changes, I will design another?

**Comment by kanchi12P** [comment]
@avinashkranjan 
added some more logos (created other new pr for that)
in pr#100
please review and if required some other please let me know what changes you want I will make some more

**Pull request closed without merging**
