### PR TITLE
Added SplashScreen for Android

### LINKED ISSUE #23: Adding Splash Screen
Adding a Splash Screen for android
I would like to work on this issue
For more info, you can visit
https://flutter.dev/docs/development/ui/advanced/splash-screen

### PR DESCRIPTION
**Pull request by HimeshNayak**
- Fixes #23 

Please let me know if anything else is needed.

### CODE REVIEW

**Comment by avinashkranjan** [comment]
I tired it... It makes the app experience a little slow and I feel like it's not needed... So I'm marking this changes as invalid and closing the PR.. But If You have some other ideas feel free to share.. Till then this PR is open @HimeshNayak

**Comment by HimeshNayak** [comment]
The splash screen the white screen that comes before the app is loaded. So, I don't it would make the app slow. Maybe the graphic was heavy to load and thus it is taking some time. We could replace it with the app icon and I guess that would solve the problem.
@avinashkranjan

**Comment by avinashkranjan** [comment]
That would be much better...plain black page with only the logo..

**Comment by HimeshNayak** [comment]
> That would be much better...plain black page with only the logo..

Yup.... will do that and send the PR.

**Comment by HimeshNayak** [comment]
Done. Have a look @avinashkranjan

**Review by avinashkranjan — APPROVED** [review]

**Pull request merged**
