### PR TITLE
Add New Class Manually by user with Separate Day

### LINKED ISSUE #145: Add Class Schedule Manually by the User
**Is your feature request related to a problem? Please describe.**
Users Can Manually add Class Schedules to complete their task.... This is the extended version of #129 .....

**Describe the solution you'd like**
A segment of the app involves where the user can add a class schedule manually and that store in firestore with corresponding user data.....

**Describe alternatives you've considered**
Mentioned Above

**Additional context**
I am also a GSSOC21 participant... If I can forward with that.... Please assign me to here.....

Thanks @HimeshNayak @avinashkranjan

### PR DESCRIPTION
**Pull request by SamarpanCoder2002**
# Description

Feature Added:
1.  User Can Manually Add New Class.
2.  User can Add Classes for separate days.
3.  For Add new class, date automatically added.
4.  Some Coding Structure changed of that specific.

Fixed Feature:
1. Change the show class List With Stream as Fetch Real-Time Update.
2. Make Heading Some Comfortable with side pictures.

### Note: Classes will add under `classes under uid` not under `classes under Particular College`(Please take a look firestore structure)

firestore structure

## Fixes #145

Replace `#145` with the issue number which is fixed in this PR

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Friday/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

<p>

</p>

Hope you will review it soon @HimeshNayak and will merge it soon @avinashkranjan

### CODE REVIEW

**Review by oshi36 — APPROVED** [review]
Great work @SamarpanCoder2002 , LGTM @avinashkranjan please merge it

**Comment by SamarpanCoder2002** [comment]
> Great work @SamarpanCoder2002 , LGTM @avinashkranjan please merge it

Thanks for review .... Hope you merge it soon @avinashkranjan

**Review by HimeshNayak — CHANGES_REQUESTED** [review]
Good Work! @SamarpanCoder2002!

But when I try to add a class, it shows me an unhandled exception about the containKey being called on null. Do check it and send the PR again.
```
I/flutter (19194): Proceed
E/flutter (19194): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: NoSuchMethodError: The method 'containsKey' was called on null.
E/flutter (19194): Receiver: null
E/flutter (19194): Tried calling: containsKey("2021-04-14")
E/flutter (19194): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
E/flutter (19194): #1      ClassesDBServices.addNewClassToFireStore (package:class_manager/services/classes_db_services.dart:28:28)
E/flutter (19194): <asynchronous suspension>
E/flutter (19194): #2      _ClassesScreenState.addNewClass.<anonymous closure>.<anonymous closure> (package:class_manager/screens/classes_screen.dart:400:29)
E/flutter (19194): <asynchronous suspension>
E/flutter (19194): 
```

I had entered the following values.
Screenshot_20210414_175659

**Comment by SamarpanCoder2002** [comment]
> Good Work! @SamarpanCoder2002!
> 
> But when I try to add a class, it shows me an unhandled exception about the containKey being called on null. Do check it and send the PR again.
> 
> ```
> I/flutter (19194): Proceed
> E/flutter (19194): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: NoSuchMethodError: The method 'containsKey' was called on null.
> E/flutter (19194): Receiver: null
> E/flutter (19194): Tried calling: containsKey("2021-04-14")
> E/flutter (19194): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
> E/flutter (19194): #1      ClassesDBServices.addNewClassToFireStore (package:class_manager/services/classes_db_services.dart:28:28)
> E/flutter (19194): <asynchronous suspension>
> E/flutter (19194): #2      _ClassesScreenState.addNewClass.<anonymous closure>.<anonymous closure> (package:class_manager/screens/classes_screen.dart:400:29)
> E/flutter (19194): <asynchronous suspension>
> E/flutter (19194): 
> ```
> 
> I had entered the following values.
> Screenshot_20210414_175659

Ok I will check it

**Comment by SamarpanCoder2002** [comment]
Hello @HimeshNayak @avinashkranjan .... I fixed that bug....Please review and merge it.... Nice to work with that project...

**Comment by SamarpanCoder2002** [comment]
Hello @HimeshNayak ...please review the pull request... I already made changes according to you

**Review by HimeshNayak — APPROVED** [review]
Great Work! @SamarpanCoder2002 
LGTM... @avinashkranjan you may merge this PR

**Comment by SamarpanCoder2002** [comment]
> Great Work! @SamarpanCoder2002
> LGTM... @avinashkranjan you may merge this PR

Thanks a lot @HimeshNayak .... Hopw you merge it soon @avinashkranjan

**Review by avinashkranjan — APPROVED** [review]
LGTM..Great Work @SamarpanCoder2002 , Just Resolve the Conflicts as UI of Classes Page has been updated

**Comment by SamarpanCoder2002** [comment]
Hello @avinashkranjan ..... I resolved the conflict and now it's works fine.....



One request @avinashkranjan .... If there is someone working on same file isuue.... Please alert me at the time of assigning in issue... Because my previous code works fine....But for that conflicts, it almost take 3 hr to refactor the code and manage it properly.....

Hope you understand @avinashkranjan

**Comment by avinashkranjan** [comment]
@SamarpanCoder2002  Will let you know, If it happens in future..

**Review by avinashkranjan — APPROVED** [review]
LGTM..🚩

**Comment by SamarpanCoder2002** [comment]
> LGTM..🚩

Thanks a lot

**Pull request merged**
