### PR TITLE
Added image picker

### LINKED ISSUE #68: Add image picker to profile_screen
**Profile Image of the user**
Add image picker to the profile_screen, store the image in the Firebase Storage and display the image accordingly where ever it is called. 

Participants of GSSOC21 willing to work on this issue can comment here and I will assign it to you.

If you need any assistance / guidance, do tell.

### PR DESCRIPTION
**Pull request by D-Ajay-Kumar**
# Description

Added image picker on profile screen to select image from gallery. The image gets updated on the home and profile screen and also the doc on firestore gets updated too.

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Friday/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by D-Ajay-Kumar** [comment]
Could anyone please merge this if the code's fine?

**Review by HimeshNayak — APPROVED** [review]
Great Work @D-Ajay-Kumar 
LGTM @avinashkranjan you may merge this PR

**Comment by avinashkranjan** [comment]
@D-Ajay-Kumar Kindly Resolve the Conflicts

**Comment by D-Ajay-Kumar** [comment]
Done @avinashkranjan

**Comment by D-Ajay-Kumar** [comment]
Wait. There seems to be some mistake. Lemme rectify that.

**Comment by D-Ajay-Kumar** [comment]
Now it's all good. Check the code please @avinashkranjan :)

**Review by avinashkranjan — APPROVED** [review]
LGTM..🚩

**Pull request merged**
