### PR TITLE
Dropdown for Courses, Stream Added with add data to firebase

### LINKED ISSUE #112: Dropdown for Course, Stream in SignUp
Its an extension of Issue #97 
Adding dropdowns for course and stream which are present in a particular college document.
If the data is not there, then provide the user with an option to enter the details and add it to the database.
Please add required checks for the data that is fetched and added to the database.

Please comment here, if you want to work on it under GSSOC21.

### PR DESCRIPTION
**Pull request by SamarpanCoder2002**
# Description

What I Introduce/ Change:
1. If Colleges not in list, then user can manually add college name(Same for Courses and Department)
2. Proper Structurize data in firebase to fetch at the time of sign_up_form_additional_details
3. Profile Screen Error Solved(I have to do it due to work flexibility... That gives unexpected error)
4. Some small bugs fixed(Raise due to old plugin version)

## Fixes #112  

Replace `#112` with the issue number which is fixed in this PR

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Friday/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [ ] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

<p>

</p>

Hope you will review it soon @HimeshNayak .... and will merge it soon @avinashkranjan

### CODE REVIEW

**Review by HimeshNayak — APPROVED** [review]
Great Work! @SamarpanCoder2002 

LGTM @avinashkranjan You may merge this PR.

**Comment by SamarpanCoder2002** [comment]
> Great Work! @SamarpanCoder2002
> 
> LGTM @avinashkranjan You may merge this PR.

Thanks for review @HimeshNayak ... Hope you merge it soon @avinashkranjan

**Comment by avinashkranjan** [comment]
Hey @SamarpanCoder2002 Kindly Resolve the Conflicts

**Review by avinashkranjan — APPROVED** [review]

**Comment by SamarpanCoder2002** [comment]
Thanks for merge bro @avinashkranjan .... Nice to work with that project

**Pull request merged**
