### PR TITLE
Created homework_screen.dart

### LINKED ISSUE #7: Homework alerts view all button and screen for all given homeworks under #SWoC 2021
there are only two homework assignments given till now, a view all button could be added below that (viz. added as a text currently) which could navigate to the screen with all homework assignments 

I will be glad to work on it under #SWoC 2021

### PR DESCRIPTION
**Pull request by HimeshNayak**
Fixes #7 
- Created homework_screen.dart
- Made View all a button, to push navigator to HomeworkScreen

### CODE REVIEW

**Comment by avinashkranjan** [comment]
Add a SS for the Changes @HimeshNayak

**Comment by HimeshNayak** [comment]
Here you go.
image

**Comment by avinashkranjan** [comment]
No Option for Going back to previous page..Create a backarrow and navbar of the app

**Comment by HimeshNayak** [comment]
In the navbar, which icon should correspond to this page? 3rd icon or 4th?

**Comment by avinashkranjan** [comment]
> In the navbar, which icon should correspond to this page? 3rd icon or 4th?

3rd Icon

**Comment by HimeshNayak** [comment]
If we have a navbar, do we still need the backbutton?

**Comment by avinashkranjan** [comment]
> If we have a navbar, do we still need the backbutton?

No No, It'll redirect to the third icon from the 1st icon on the navbar..We don't need back button..

**Comment by HimeshNayak** [comment]
Done
image

**Review by avinashkranjan — APPROVED** [review]
LGTM..

**Comment by avinashkranjan** [comment]
Hey @HimeshNayak, when this is redirected from `view all` in the **HomeScreen** the navbar seems to be missing....Fix that issue

**Comment by HimeshNayak** [comment]
I have added this issue - #26 
Fixed it - #27

**Comment by avinashkranjan** [comment]
@HimeshNayak I'd Like Few more changes in this page, would you be able to do that. And Make Similar changes in Test Alerts Page (#34) .. I've added new Icon in Navbar for that page.... So the change I'm asking for is the page looks too plain Hav a look at other pages and follow that theme i.e darker color for the parent element and then and overlay over that with a lighter color.

**Comment by avinashkranjan** [comment]
@HimeshNayak I'd Like Few more changes in this page, would you be able to do that. So the change I'm asking for is the page looks too plain Hav a look at other pages and follow that theme i.e darker color for the parent element and then and overlay over that with a lighter color.

**Comment by HimeshNayak** [comment]
Okay I'll add this as an issue and then send a PR to solve it.

**Comment by avinashkranjan** [comment]
> Okay I'll add this as an issue and then send a PR to solve it.

Okay, Great

**Pull request merged**
