### PR TITLE
Facebook Authentication Added With Exception Handling( #71 )

### PR DESCRIPTION
**Pull request by SamarpanCoder2002**
# Description

I add Facebook Authentication With Exception Handling and also added exception handling with google Auth(Google Auth issue was raised by me 2 or 3 days ago and also pull request get merged(#58)).

## Fixes # (#71)

Replace ` #71 ` with the issue number which is fixed in this PR

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Friday/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

<p align="center">
onboarding screen pic
Facebook Log-In Screen Pic
</p>

### CODE REVIEW

**Review by HimeshNayak — CHANGES_REQUESTED** [review]
Very well done @SamarpanCoder2002 

But there is a bug in the log out for facebook. When tapping logout button, the user is logged out (as per the logs), but the screen does not go to the main screen Please fix that and send the PR.
image

**Comment by SamarpanCoder2002** [comment]
> Very well done @SamarpanCoder2002
> 
> But there is a bug in the log out for facebook. When tapping logout button, the user is logged out (as per the logs), but the screen does not go to the main screen Please fix that and send the PR.
 
@HimeshNayak  @avinashkranjan ..... Please check now..I fixed the log out bug.... Now that working Fine.... Thanks for the review @HimeshNayak

**Review by HimeshNayak — APPROVED** [review]
Reviewed the changes. Working fine!! 
LGTM... @avinashkranjan you can merge this PR

**Comment by SamarpanCoder2002** [comment]
> Reviewed the changes. Working fine!!
> LGTM... @avinashkranjan you can merge this PR

Thanks for the review  @HimeshNayak ..... Waiting for the merge of that pull request @avinashkranjan .... and also please merge the pull request of other related to padding in the log out button(Without that working is really frustrating at the time of log out).... Thank you @avinashkranjan

**Review by avinashkranjan — APPROVED** [review]
LGTM..Great Work @SamarpanCoder2002

**Pull request merged**
