### PR TITLE
Added Firebase to Android

### LINKED ISSUE #10: Attaching Firebase as a Backend
As of now backend is not attached to the app. We can use Firebase as a backend. Please assign this issue to me under SWOC.

### PR DESCRIPTION
**Pull request by HimeshNayak**
- Fixes #10
- added Android app to the Firebase project friday-683ad  
- added firebase_core: ^0.5.3 to pubspec.yaml
- initialized firebase app in main
- updated minSdkVersion to 21 from 16

### CODE REVIEW

**Comment by HimeshNayak** [comment]
I have added "Friday IOS" and "Friday Android" apps to the Firebase Project.  Please have a look and let me know if anything else is needed.

**Review by infiniteoverflow — APPROVED** [review]

**Comment by infiniteoverflow** [comment]
Reviewed !! @avinashkranjan You are good to go with this PR.

But GitGuardian might raise an issue with the Google Services Json and Plist file. Need to do the necessary for that.

**Review by Nikunj-Aggarwal — APPROVED** [review]
Avinash Sir, I think you can merge this PR

**Review by avinashkranjan — APPROVED** [review]
LGTM..💯

**Comment by avinashkranjan** [comment]
@all-contributors please add @HimeshNayak  for code

**Pull request merged**
