### PR TITLE
Now Firestore can't affect by Scammers

### LINKED ISSUE #134: FireStore can affected by Scammers
**Is your feature request related to a problem? Please describe.**
In this app, If anybody signup(With Email and Password), details directly added to the firestore.... Now anybody can signup with some invalid email with that signup for scamming and pressure on firestore unnecessarily increases.

**Describe the solution you'd like**
For Signup(Email and Password Auth), after signup, user directly navigate to the log-in page.....After Email verification, is user login properly, check in the firestore that UID is present or not...If not, then user navigate to the `sign_up_additional` page and now data can store in firestore.... If yes, then user navigate to the bottom navigation page....

That can reduce the scammers activity effect on firestore....because, now If user log-in properly with email verification, then only data add to firestore...........Not at the time of sign-up as invalid email can use for signup

**Describe alternatives you've considered**
Described Above

**Additional context**
I am also a `GSSOC'21` participant.....If I can forward with that.....Please assign me to here....

Thanks @avinashkranjan @HimeshNayak

### PR DESCRIPTION
**Pull request by SamarpanCoder2002**
# Description

What I made Changes:-

1. Now After User SignUp, the user navigates to the `log-in` page instead of the `additional_details` page.
2. If User Log-in Successfully with Verification, then
                         2.1) If user data is present in firestore, they navigate to the `bottom_navigation` page.
                         2.2) If absent, Then User Switch to the `Sign-up-additional-details` page and then the `bottom_navigation` page.

3. On the `Sign-Up-Form-Additional-Details` page, I changed `Sign-up` heading to `Additional Details` and at the bottom, the `Sign Up` button to the `Save` button, as after log-in, take additional information with title and button named as `Sign Up` does not make a sense...

## Fixes #134

Replace `#134` with the issue number which is fixed in this PR

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Friday/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

<p>

</p>

I am also a GSSOC21 particiapant....Please raise the required labels for that program.

Hope you review it soon @HimeshNayak and merge it soon @avinashkranjan

### CODE REVIEW

**Review by HimeshNayak — APPROVED** [review]
Great @SamarpanCoder2002 !
LGTM @avinashkranjan you may merge this PR

**Comment by SamarpanCoder2002** [comment]
> Great @SamarpanCoder2002 !
> LGTM @avinashkranjan you may merge this PR

Thanks for review @HimeshNayak .... Hope you merge it soon @avinashkranjan

**Review by avinashkranjan — APPROVED** [review]
LGTM..💯

**Comment by SamarpanCoder2002** [comment]
> LGTM..💯

Thanks for merge

**Pull request merged**
