### PR TITLE
Refactored onboarding_page.dart

### PR DESCRIPTION
**Pull request by ishanailwal**
# Description

Refactored the code in the "onboarding page"

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Friday/blob/master/CONTRIBUTING.md)?

- [x] Yes

## Type of change

_Please delete options that are not relevant._

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by ishanailwal** [comment]
@HimeshNayak Okay!

**Comment by ishanailwal** [comment]
@HimeshNayak Done!

**Review by HimeshNayak — APPROVED** [review]
LGTM... @avinashkranjan you can merge this PR.

**Review by HimeshNayak — APPROVED** [review]

**Review by avinashkranjan — APPROVED** [review]
LGTM

**Comment by avinashkranjan** [comment]
@all-contributors please add @ishanailwal for code

**Pull request merged**
