### PR TITLE
Adding API for sending user queries through contact us page

### LINKED ISSUE #355: Feat: Updating "Contact Us" page and adding an API for the "Contact Us" button to work.
### Describe the feature

I'd implement a google sheet where the user's contact us queries would be stored when they would be submitted from the application. The google sheet would be accessable via a RESTful API which I'd create in order to connect it with the application and send the user's queries through this API. I'd also create new blocks in the same page, which would include:

- an ```email``` block, for taking the user's email
- a ```timestamp```, for taking the timestamp of the query.
- a ```name``` block, for taking the user's name. 

### Add ScreenShots

Screenshot 2023-07-21 at 2 27 26 PM

Screenshot_20230721_142639

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by jaivsh**
# Description

I've implemented the google sheetds API to push the user queries data filled by the user from the ```contact us``` page to the Google sheet. From this sheet, whatever queries posted by the users, along with their email and their timestamp of posting would be displayed in this sheet. 

Sheet link: https://docs.google.com/spreadsheets/d/14ewMrJbsoadMUTvUEEVffVBh1KqrEy0wZ_MrAtdYU_A/edit?usp=sharing

This API has been created by using the ```scripts``` feature of google sheets, where i created the relevant functions and deployed them for use. The sheet is open for anyone currently. The steps for making it private to Friday application owners are as follows:
- Open the sheet in the owner's Google account.
- Then, open the scripts module from ```Extension``` -> ```App Script```. 
- Create new deployment as Web-App. 
- In execute as, select the relevant email address, and in "Who has access", select "Myself". This would restrict access to app's owners. The sheet can then be opened and edited by apps owners only. 

 
Screenshot 2023-07-27 at 5 05 50 AM

From this sheet, all the user queries submitted by the user can be viewed and worked upon. 

Screenshot_20230727_045918

Screenshot 2023-07-27 at 5 12 26 AM

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Friday/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by jaivsh** [comment]
@avinashkranjan please review this PR!

**Review by avinashkranjan — APPROVED** [review]

**Comment by avinashkranjan** [comment]
@jaivsh Resolve the Conflict

**Comment by jaivsh** [comment]
> @jaivsh Resolve the Conflict

just 1 sec

**Comment by jaivsh** [comment]
@avinashkranjan done!

**Pull request merged**
