### PR TITLE
Progress Graph added

### LINKED ISSUE #64: add a progress graph
Can we add a progress graph so that we can track our marks and work according to that?

### PR DESCRIPTION
**Pull request by andoriyaprashant**
# Description

The Assignment Progress Chart is a new feature added to the Home Screen of the app. It allows users to track their assignment progress visually through a chart representation. The chart displays the scores of completed assignments over time, helping users to monitor their performance and identify trends.

Here is the demo Screenshot - 

aed2d82c-a272-482f-82ba-0642c627588d

The chart is placed within the Home Screen, providing users with a comprehensive overview of their recent alerts and homework, along with the visual representation of their assignment progress. The feature enhances the user experience by providing an intuitive and engaging way to track progress.

Additionally, the feature includes labels for the horizontal and vertical lines in the chart. The horizontal line is labeled as "Progress Line" to indicate the trend of assignment scores over time. The vertical line is labeled as "Score Reference Line" to provide a reference for score comparison at each data point.

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Friday/blob/master/CONTRIBUTING.md)?

-  Yes
- [ ] No

## Type of change

-  New feature (non-breaking change which adds functionality)

## Checklist:

-  My code follows the style guidelines(Clean Code) of this project
-  I have performed a self-review of my own code
-  My changes generate no new warnings
-  I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by avinashkranjan — APPROVED** [review]

**Comment by avinashkranjan** [comment]
Resolve the Conflicts @andoriyaprashant

**Comment by andoriyaprashant** [comment]
i think the conflicts are bcz of this 
Screenshot 2023-07-10 212647

image

It seems that in a previous merged pull request, some dependencies were accidentally removed by someone, which resulted in merge conflicts between the branch of my pull request and the main branch.

I create an issue on this and solve it, maybe after that there won't be any merge conflicts in my pull request.
Thank you @avinashkranjan

**Comment by andoriyaprashant** [comment]
I have re-added the dependencies. You can review them in this pull request #331 . After merging this, it will also resolve the merge conflicts with this pull request.
Thank you

**Comment by andoriyaprashant** [comment]
Hello @avinashkranjan I have now resolved the merge conflicts that were occurring due to the 'home_screen.dart' file. Please take a look at them once

**Pull request merged**
