### PR TITLE
Adds Authentication Services

### LINKED ISSUE #11: Adding Authentication feature in the app under SWoC 2021
The current version of the app does not have any authentication feature. I would like to work on this issue to add the authentication feature in the application. The idea is to build and design the Login and Signup page that will allow users to either signup or login to the app using Email id and Password or using Google Authenication.

### PR DESCRIPTION
**Pull request by Imadarshsri**
This integrates the _Firebase Authentication_ services to the application by adding `Onboarding`, `Login`, and `Signup` Pages.

**Following tasks accomplished:** 
- Adds `Login`, `Signup`, and `Onboarding` Pages.
- Implements designs given by @purnima143
- Fixes #11, #14 and #21

### CODE REVIEW

**Comment by Imadarshsri** [comment]
@avinashkranjan Please review it and let me know if there is an issue...

**Review by avinashkranjan — APPROVED** [review]
LGTM..💯..Great Job @Imadarshsri

**Comment by avinashkranjan** [comment]
@all-contributors please add @Imadarshsri for code

**Comment by Imadarshsri** [comment]
Thanks...@avinashkranjan :smile:

**Pull request merged**
