### PR TITLE
Now user data gets fetched on first login

### LINKED ISSUE #118: Data is not fetched at first login
**Describe the bug**
When the user logins for the first time in the app, the user data is not properly fetched and the default text is displayed.

**To Reproduce**
1. Clear data of the app.
2. Run the app on the emulator
3. Login with email and password
4. See Error: On Home Page It shows 'Hello Sir' rather than the name of the user and on profile page it shows loading...

**Expected behavior**
The data should be fetched properly as it is fetched when the app is restarted.

**Screenshots**
Screenshot_20210325_122052
Screenshot_20210325_122127
Screenshot_20210325_122133

**Additional context**
Anyone who wants to work on this issue under GSSOC21, kindly comment here and I will assign you the issue.

### PR DESCRIPTION
**Pull request by D-Ajay-Kumar**
# Description
Now user data gets fetched on first login which earlier wasn't happening.

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Friday/blob/master/CONTRIBUTING.md)?

- [x] Yes

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by D-Ajay-Kumar** [comment]
Let me know if any changes are required @HimeshNayak @avinashkranjan

**Review by HimeshNayak — CHANGES_REQUESTED** [review]
@D-Ajay-Kumar, I had implemented your changes in the code. But it does not seem to work. Please check. I am attaching the ss for your reference.

image


Note that the user is logged in, still the profilePictureUrl is called on null and the name in the homepage is also not there.

**Comment by D-Ajay-Kumar** [comment]
Hi, sorry about the delay, I had a couple of tests at college. I'll rectify the code.

**Comment by D-Ajay-Kumar** [comment]
Also a small request, I have created two accounts using the emails
- dajayk12@gmail.com
- dajayk123@gmail.com

Can you please delete both the accounts so that I can create them from scratch to test the code? I've run out of email accounts.

**Comment by HimeshNayak** [comment]
> Also a small request, I have created two accounts using the emails
> 
> * [dajayk12@gmail.com](mailto:dajayk12@gmail.com)
> * [dajayk123@gmail.com](mailto:dajayk123@gmail.com)
> 
> Can you please delete both the accounts so that I can create them from scratch to test the code? I've run out of email accounts.

Done

**Comment by D-Ajay-Kumar** [comment]
Aight got the error! This should fix the problem.

If the user is null then the next condition won't be checked and hence no getter will be called on the null user object.

code

**Review by HimeshNayak — APPROVED** [review]
@D-Ajay-Kumar You have fixed the problem with the photo when the user is null. I am approving this PR now. But can there be a way to open the app only after the user is not null?

LGTM @avinashkranjan you may merge this PR.

**Review by avinashkranjan — APPROVED** [review]
LGTM..💯

**Comment by HimeshNayak** [comment]
> > @D-Ajay-Kumar You have fixed the problem with the photo when the user is null. I am approving this PR now. But can there be a way to open the app only after the user is not null?
> > LGTM @avinashkranjan you may merge this PR.
> 
> It can be done @HimeshNayak but then we'd have to have the Consumer around everything that's loaded after login and make it show a circular progress indicator while the user data gets loaded. The drawback though would be that in the future if we add the feature to change user's photo or name then the all the screens will rebuild. Currently, since the consumer is just around name and photo, changing them would only rebuild these two widgets. That's why it's better the way it is now. If you have a better method then please do let me know I'd love to have a second opinion.

Okay, I'll look into it once again. For now, let it be this way.

**Pull request merged**
