### PR TITLE
Google Authentication With Authenticate Data Store in FireStore Added

### PR DESCRIPTION
**Pull request by SamarpanCoder2002**
Hello, I added the following functionality:
1. Google Authentication Through Firebase
2. Store Authenticate Data to FireStore

This pull request is associated with issue(https://github.com/avinashkranjan/Friday/issues/58#issue-826459134)
Hope you will merge it...If there any problem, you can freely tell me......

This is an amazing project to work with.... I will like to add more functionality and design Flexibility very soon.... I will raise a new issue very soon.... Hope you will permit me to do that...Thanks

### CODE REVIEW

**Review by HimeshNayak — CHANGES_REQUESTED** [review]
Good Work! @SamarpanCoder2002 

Please look at these changes and implement them
1. Send the record of the user in the users collection only.
2. After the google login the user is directly sent to the home page and the academic details are never entered by the user. Once logged in take the user to the signup_additional_details_screen, if the user hasn't entered the details.  
3. The heading of the AlertBox can be more professional. Like : Logged In 
4. Lastly, do not change the styling in this PR. That can be done in other issue.
Screenshot_20210312_133419

@avinashkranjan If you want to add anything, please do.

**Comment by SamarpanCoder2002** [comment]
> Good Work! @SamarpanCoder2002
> 
> Please look at these changes and implement them
> 
> 1. Send the record of the user in the users collection only.
> 2. After the google login the user is directly sent to the home page and the academic details are never entered by the user. Once logged in take the user to the signup_additional_details_screen, if the user hasn't entered the details.
> 3. The heading of the AlertBox can be more professional. Like : Logged In
> 4. Lastly, do not change the styling in this PR. That can be done in other issue.
>    Screenshot_20210312_133419
> 
> @avinashkranjan If you want to add anything, please do.

Thanks for that review..I will made changes soon

**Comment by SamarpanCoder2002** [comment]
> Good Work! @SamarpanCoder2002
> 
> Please look at these changes and implement them
> 
> 1. Send the record of the user in the users collection only.
> 2. After the google login the user is directly sent to the home page and the academic details are never entered by the user. Once logged in take the user to the signup_additional_details_screen, if the user hasn't entered the details.
> 3. The heading of the AlertBox can be more professional. Like : Logged In
> 4. Lastly, do not change the styling in this PR. That can be done in other issue.
>    Screenshot_20210312_133419
> 
> @avinashkranjan If you want to add anything, please do.

I made the changes according to your instruction @HimeshNayak ..... Please check it out and if there no problem .... pls merge it....If any problem occurs, you can freely tell me..... Thanks for giving me chance to contribute here..

**Review by HimeshNayak — APPROVED** [review]
Great! @SamarpanCoder2002 
LGTM @avinashkranjan you can merge this PR.

**Comment by SamarpanCoder2002** [comment]
> Great! @SamarpanCoder2002
> LGTM @avinashkranjan you can merge this PR.

Thanks for the review @HimeshNayak ...... waiting for merge @avinashkranjan .....That really a nice experience to work with

**Review by avinashkranjan — APPROVED** [review]
LGTM..💯..Great Job @SamarpanCoder2002

**Comment by avinashkranjan** [comment]
@all-contributors please add @SamarpanCoder2002 for code

**Comment by SamarpanCoder2002** [comment]
> @all-contributors please add @SamarpanCoder2002 for code

Thanks for that

**Pull request merged**
