### PR TITLE
Now After Google/FB Sign-in user navigate to `additional details` page and then `bottom navigation` page instead of `log-in` page

### LINKED ISSUE #128: After first Google/FB Sign-in, user navigate to the `log-in` page instead of `bottom_navigation` page
**Is your feature request related to a problem? Please describe.**
If user First Time Sign-in with Google or Facebook, then user navigate to the `sign-up-additional page`...it's ok....But then they navigate to the log-in page.... That's not right I think.... In that two kinds of sign-in, after sign-up-additional details(at the time of first sign-in), user have to directly navigate to the `bottom_navigation` page instead of `log-in` page ..... I want to make it possible..

**Describe the solution you'd like**
After Google or FB sign-in, 
1. For first time, after `sign-up-form-additional-details`, user have to be navigate to the `bottom_navigation` page.......

For not first time, user directly navigate to `bottom_navigation` page after sign-in

**Describe alternatives you've considered**
According to above solution I described

**Additional context**
I am also a GSSOC'21 participant...If I can forward with that...please assign me to here....

Thanks @HimeshNayak @avinashkranjan

### PR DESCRIPTION
**Pull request by SamarpanCoder2002**
# Description

Now After Google/FB Sign-in user navigate to `additional details` page and then `bottom navigation` page instead of `log-in` page

## Fixes #128

Replace `#128` with the issue number which is fixed in this PR

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Friday/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

Not Possible to add screenshots because this is involved in navigation process...

Hope you review it and merge it soon @HimeshNayak @avinashkranjan

### CODE REVIEW

**Comment by SamarpanCoder2002** [comment]
> Great @SamarpanCoder2002!
> LGTM! @avinashkranjan you may merge this PR

Thanks for review @HimeshNayak ...hope you merge it soon @avinashkranjan

**Comment by SamarpanCoder2002** [comment]
> > Great @SamarpanCoder2002!
> > LGTM! @avinashkranjan you may merge this PR
> 
> Thanks for review @HimeshNayak ...hope you merge it soon @avinashkranjan

@avinashkranjan kindly merge this pull reuest...Actually I can't proceed with another issue...Thank u @avinashkranjan

**Review by hareshnayak — APPROVED** [review]
Great work @SamarpanCoder2002 ! 😄 
@avinashkranjan please merge the PR 👍

**Comment by SamarpanCoder2002** [comment]
> Great work @SamarpanCoder2002 ! 😄
> @avinashkranjan please merge the PR 👍

Thanks for review @hareshnayak ..... @avinashkranjan ...Hope you merge it soon

**Review by avinashkranjan — APPROVED** [review]
LGTM..💯

**Comment by SamarpanCoder2002** [comment]
> LGTM..💯

Thanks for merge

**Pull request merged**
