### PR TITLE
Adds Animated Bottom Navigation Bar

### LINKED ISSUE #37: Animating the Navbar
# AIM
- The main purpose is the animate the navbar. So, It looks more user friendly and interactive.

# Details
- You can choose for multiple types of animation and select and code which suites the best. 
- Before you choose one and start working. Send a gif in this Issue showing what would that look like.

### PR DESCRIPTION
**Pull request by Imadarshsri**
This adds an Animated Bottom Navigation Bar.
Fixes #37.

### CODE REVIEW

**Comment by Imadarshsri** [comment]
@avinashkranjan, Please review it...

**Comment by avinashkranjan** [comment]
> @avinashkranjan, Please review it...

Add a gif of the made changes...

**Comment by Imadarshsri** [comment]
Here, have a look at it...

bottomNavBar

**Review by avinashkranjan — APPROVED** [review]

**Comment by Imadarshsri** [comment]
Thanks...@avinashkranjan

**Pull request merged**
