### PR TITLE
Form Detail Correction

### PR DESCRIPTION
**Pull request by namancoder**
In the 2nd page of signup ,  "Year" column was little ambiguous creating confusion as to which year to enter.
so I have corrected it to "Graduation Year".
Also this is my 1st PR so please bear with me , i know its a very small contribution..

### CODE REVIEW

**Comment by avinashkranjan** [comment]
Hey @namancoder No Contribution is same or large..You are always welcome to contribute if you're changing a little thing. Everyone is here to learn..
Kindly Create an Issue for the PR as I need for the documentation purposes.

**Comment by namancoder** [comment]
> Hey @namancoder No Contribution is same or large..You are always welcome to contribute if you're changing a little thing. Everyone is here to learn..
> Kindly Create an Issue for the PR as I need for the documentation purposes.

I have done it , let me know if this is the right way.

**Review by HimeshNayak — CHANGES_REQUESTED** [review]
The "Year" is the year of study in college and not graduation year. So if @avinashkranjan is okay with it, replace the "Year" to "Year of Study". The validator checks for the college year to be less than 5.
```
validator: (_) {
    int _yr = int.tryParse(_year.text);
    if (_year.text.isNotEmpty && _yr != null && _yr <= 5) {
        return null;
    }
    return "Enter valid College Year";
}
```

**Comment by namancoder** [comment]
i can change it as needed but i was not really able to make an account in the app before reading the source code and then getting the idea that the year asked is the current year i am in....making the YEAR column a little confusing for the people who are going to make and enter Year.

**Comment by namancoder** [comment]
Is their anything i need to do? i am new to this open source contribution so i dont understand some terminologies.

**Comment by HimeshNayak** [comment]
Just change "Year" to "Current Academic year" In signup and profile, and send the updated PR. 

If you need any assistance/guidance, do tell.

**Comment by namancoder** [comment]
Done the changes requested please review.

**Review by HimeshNayak — APPROVED** [review]
LGTM @avinashkranjan you can merge this PR.

**Review by avinashkranjan — APPROVED** [review]

**Comment by avinashkranjan** [comment]
@all-contributors please add @namancoder for code

**Pull request merged**
