### PR TITLE
Sign-up Log-in Email Verification Added(#81)

### PR DESCRIPTION
**Pull request by SamarpanCoder2002**
# Description

Sign-Up/ Log-In Email Verification Added..... Without Registered email verification, user can't log-in into the account.....

When User Complete sign up with email, password..... A verification email will send to the registered email.... Then User fill the signup form of additional details..... Then User Notify that, verification email send to the registered mail and verify email at first and then log in and user navigate to the log-in page..... Now user can't log-in Without email verification...... If the user not verify registered email by verification link, user can't log-in to the account....

## Fixes #( #81)

Replace `#81` with the issue number which is fixed in this PR

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Friday/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

<p>

</p>

Thanks a lot @avinashkranjan @HimeshNayak for assign me in that issue.... Hope you will review it and merged it soon.... If any problem occurs, you can freely tell me.... Thank you

### CODE REVIEW

**Review by HimeshNayak — APPROVED** [review]
Great Job! @SamarpanCoder2002 
LGTM @avinashkranjan you can merge this PR

**Comment by SamarpanCoder2002** [comment]
> Great Job! @SamarpanCoder2002
> LGTM @avinashkranjan you can merge this PR

Thanks for review @HimeshNayak ....  Hope you will merge soon @avinashkranjan

**Review by avinashkranjan — APPROVED** [review]
LGTM..🚩

**Comment by SamarpanCoder2002** [comment]
> LGTM..🚩

Thanks for merge that pull request

**Pull request merged**
