### PR TITLE
Alert Page made under issue#6

### PR DESCRIPTION
**Pull request by hareshnayak**
Alert Page has been created which will be navigated to on tapping on view all

Fixed Issue #6 
WhatsApp Image 2021-01-14 at 00 51 04 (1)
WhatsApp Image 2021-01-14 at 00 51 04

### CODE REVIEW

**Review by avinashkranjan — CHANGES_REQUESTED** [review]
Add the NavBar @hareshnayak

**Comment by hareshnayak** [comment]
Okay, let me see what i can do

**Comment by avinashkranjan** [comment]
> Okay, let me see what i can do

Any Updates??

**Comment by avinashkranjan** [comment]
> Okay, let me see what i can do

Any Updates??

**Pull request closed without merging**
