### PR TITLE
added 2 new logos

### LINKED ISSUE #56: LOGO DESIGN
I would like to make a logo for this project.
so, can I go for it?
I am GSSoC'21 participant.
please assign it to me.

### PR DESCRIPTION
**Pull request by kanchi12P**
# Description

Added 2 new logos

## Fixes #56

Replace `issue_no` with the issue number which is fixed in this PR

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Friday/blob/master/CONTRIBUTING.md)?

- [X] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [X] My changes generate no new warnings
- [X] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.
newlogo1
newlogo2

### CODE REVIEW

**Comment by kanchi12P** [comment]
@avinashkranjan  some changes requested in PR#63
added 2 new logos
please review and if required some other please let me know what changes you want I will make some more

**Comment by kanchi12P** [comment]
@avinashkranjan 
please review my pr

**Review by hareshnayak — CHANGES_REQUESTED** [review]
@kanchi12P  The design is amazing I must say. I think you can align it more with the theme of the app. Darker Shades like Blue and black can go for the background in my opinion while the text and design can be light themed.
Follow up with me if you have any further doubts or ideas.
ps: Sorry for the late review

**Comment by kanchi12P** [comment]
> @kanchi12P The design is amazing I must say. I think you can align it more with the theme of the app. Darker Shades like Blue and black can go for the background in my opinion while the text and design can be light themed.
> Follow up with me if you have any further doubts or ideas.
> ps: Sorry for the late review


> @kanchi12P The design is amazing I must say. I think you can align it more with the theme of the app. Darker Shades like Blue and black can go for the background in my opinion while the text and design can be light themed.
> Follow up with me if you have any further doubts or ideas.
> ps: Sorry for the late review

@hareshnayak thanks for the review so should I make the suggested color/theme changes in same logos i mean is their structure good or new design?

**Comment by kanchi12P** [comment]
F R I D A Y (1)
FRIDAY
@hareshnayak  what about these , how are these?

**Comment by hareshnayak** [comment]
> > @kanchi12P The design is amazing I must say. I think you can align it more with the theme of the app. Darker Shades like Blue and black can go for the background in my opinion while the text and design can be light themed.
> > Follow up with me if you have any further doubts or ideas.
> > ps: Sorry for the late review
> 
> 
> > @kanchi12P The design is amazing I must say. I think you can align it more with the theme of the app. Darker Shades like Blue and black can go for the background in my opinion while the text and design can be light themed.
> > Follow up with me if you have any further doubts or ideas.
> > ps: Sorry for the late review
> 
> @hareshnayak thanks for the review so should I make the suggested color/theme changes in same logos i mean is their structure good or new design?

Yes in my opinion we can keep the structural design... But how about using the color scheme of the icon (graduation cap nd scroll) ie.. blue white etc.

**Comment by avinashkranjan** [comment]
No Response, Closing this `PR`

**Comment by kanchi12P** [comment]
@avinashkranjan sorry I was busy with my semester exams I will update the changes today please open this

**Pull request closed without merging**
