### PR TITLE
FEAT: HomePage Search Error Issue #136

### LINKED ISSUE #136: Add search feature on homescreen
Currently, there only a textfield in the home screen for searching the content, but it's not working.
**I would like to work on this issue as a GSSOC Participant**.

### PR DESCRIPTION
**Pull request by mrmayurgithub**
## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Friday/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.
delesearch

### CODE REVIEW

**Comment by mrmayurgithub** [comment]
@oshi36 Kindly review this PR and merge it. I've added the search functionality.

**Review by oshi36 — APPROVED** [review]
ok , @mrmayurgithub good work. @avinashkranjan please merge the PR

**Review by avinashkranjan — CHANGES_REQUESTED** [review]
Hey @mrmayurgithub , LGTM, Just Change the background of the Search Page to **Dark Theme** as a **_Bright white page_** for a dark theme based app looks odd..

**Comment by mrmayurgithub** [comment]
> Hey @mrmayurgithub , LGTM, Just Change the background of the Search Page to **Dark Theme** as a **_Bright white page_** for a dark theme based app looks odd..

Sure.

**Comment by mrmayurgithub** [comment]
@avinashkranjan I've made some minor changes. But I am unable to change the background color, as I don't know completely about searchDelegate in Flutter. 
**I think creating another issue regarding this will help, and maybe someone else will work on it.**
So, Kindly merge the PR, as I've implemented the search function successfully.

**Comment by SamarpanCoder2002** [comment]
> @avinashkranjan I've made some minor changes. But I am unable to change the background color, as I don't know completely about searchDelegate in Flutter.
> **I think creating another issue regarding this will help, and maybe someone else will work on it.**
> So, Kindly merge the PR, as I've implemented the search function successfully.

in the Scaffold, use `background color: ` as `Theme.of(context).backgroundColor`.... hope it helps

**Comment by mrmayurgithub** [comment]
> > @avinashkranjan I've made some minor changes. But I am unable to change the background color, as I don't know completely about searchDelegate in Flutter.
> > **I think creating another issue regarding this will help, and maybe someone else will work on it.**
> > So, Kindly merge the PR, as I've implemented the search function successfully.
> 
> in the Scaffold, use `background color: ` as `Theme.of(context).backgroundColor`.... hope it helps

I haven't used any Scaffold or something for the search screen, I've extended a class called DataSearch wth SearchDelegate, that's provided by Flutter. And I think we can only use overrides in that class. I knew about the appbartheme override, so I have changed the background color in appbar.

**Comment by mrmayurgithub** [comment]
@avinashkranjan Kindly, merge the PR. I have been giving my exams, so I am still a little bit busy. I think someone will surely solve this background colour issue in Level 0.

**Pull request merged**
