### PR TITLE
Wiki Pages Added as README File

### LINKED ISSUE #76: Wiki Page
Create a Wiki Page for the project.

Anyone who wants to work on this issue under GSSOC21, comment here and I'll assign it to you.
You can refer : https://guides.github.com/features/wikis/ for getting more info on Wiki Pages.

### PR DESCRIPTION
**Pull request by SamarpanCoder2002**
Added WIKI Pages

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #76 

Replace #76 with the issue number which is fixed in this PR

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Friday/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

Hope you review it @HimeshNayak  and merge it @avinashkranjan  soon

### CODE REVIEW

**Review by HimeshNayak — APPROVED** [review]
Great @SamarpanCoder2002 
LGTM @avinashkranjan you can merge this PR and if there are any changes regarding wiki pages that can be added in this file only and I will copy that to the wiki page of the project.

**Comment by SamarpanCoder2002** [comment]
> Great @SamarpanCoder2002
> LGTM @avinashkranjan you can merge this PR and if there are any changes regarding wiki pages that can be added in this file only and I will copy that to the wiki page of the project.

Thanks for review...hope you will merge it soon @avinashkranjan

**Review by avinashkranjan — APPROVED** [review]

**Comment by avinashkranjan** [comment]
@HimeshNayak You can copy this to Wiki Page...

**Comment by SamarpanCoder2002** [comment]
> @HimeshNayak You can copy this to Wiki Page...

Thanks for merge

**Comment by HimeshNayak** [comment]
> @HimeshNayak You can copy this to Wiki Page...

Okay 👍

**Pull request merged**
