### PR TITLE
Fixed Issue#33

### LINKED ISSUE #33: Pixels overflowing in Login Page
Here is the ss
image

Please assign this issue to me under SWoC.

### PR DESCRIPTION
**Pull request by HimeshNayak**
- Fixes #33 

Here is the ss
image

### CODE REVIEW

**Comment by avinashkranjan** [comment]
Great @HimeshNayak

**Review by avinashkranjan — CHANGES_REQUESTED** [review]
Change it from `hardcoded` values to `MediaQuery.of(context)` Values.. It would make it more flexible.

**Comment by HimeshNayak** [comment]
Okay sure! Will do.

**Review by avinashkranjan — CHANGES_REQUESTED** [review]
Change Vertically Values to Similarly

**Comment by HimeshNayak** [comment]
Done @avinashkranjan 
Please check and tell me if anything else is needed.
image

**Comment by avinashkranjan** [comment]
> Done @avinashkranjan 

Told you in the comment above

**Comment by HimeshNayak** [comment]
> Change Vertically Values too Similarly

In my opinion, vertical values shouldn't be changed because when the screen size changes then padding around text would change which might not look as appealing as it is now.
Still, you make the final call.

**Comment by avinashkranjan** [comment]
> > Similarly, Change Vertical Values too
> 
> In my opinion, vertical values shouldn't be changed because when the screen size changes then padding around text would change which might not look as appealing as it is now.
> Still, you make the final call.

Okay Then as of now let it be..If any issue arises I'll let you know..

**Review by avinashkranjan — APPROVED** [review]

**Comment by HimeshNayak** [comment]
> > > Similarly, Change Vertical Values too
> > 
> > 
> > In my opinion, vertical values shouldn't be changed because when the screen size changes then padding around text would change which might not look as appealing as it is now.
> > Still, you make the final call.
> 
> Okay Then as of now let it be..If any issue arises I'll let you know..

Sure!

**Pull request merged**
