### PR TITLE
Profile Overlay added under issue #8

### PR DESCRIPTION
**Pull request by hareshnayak**
The profile overlay will open on tapping on the profile pic in the header
this is under issue #8 

Please tell if any change is required

### CODE REVIEW

**Comment by avinashkranjan** [comment]
Add a SS of the changes @hareshnayak

**Comment by hareshnayak** [comment]
Will do 👍

**Comment by avinashkranjan** [comment]
@hareshnayak ??

**Comment by hareshnayak** [comment]
WhatsApp Image 2021-01-13 at 21 29 43
WhatsApp Image 2021-01-13 at 21 29 43 (1)

https://user-images.githubusercontent.com/61956975/104477247-e2275680-55e6-11eb-85d7-5b6b0530d86d.mp4

**Comment by avinashkranjan** [comment]
@hareshnayak I thought You were going to make profile page not just mere profile overlay with logout option... If you want Design for the page I can get you that and then you code...

**Comment by hareshnayak** [comment]
Okay then you can send me the Design then I'll get started on that

**Pull request closed without merging**
