### PR TITLE
Changed college textfield to dropdown with dropdown values from firebase

### LINKED ISSUE #95: Replace TextField with dropdown in signup for college details
**Is your feature request related to a problem? Please describe.**
To reduce the ambiguity of college entries in the database. Only registered colleges should appear for the user to select when signing up in the app.

**Describe the solution you'd like**
Replace TextField with dropdown in signup for college details so that the user can select the details from there.
The registered colleges will have the following database.
image

**Additional context**
Open to suggestions. Anyone willing to work on this issue under GSSOC21 may comment below and I'll assign it to you. If you need more explanation / guidance, do tell.

### PR DESCRIPTION
**Pull request by D-Ajay-Kumar**
# Description

Changed the college textfield in sign up page to a dropdown button which gets it's dropdown values from firebase's 'colleges' collection.

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Friday/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

WhatsApp Image 2021-03-16 at 7 24 19 PM
WhatsApp Image 2021-03-16 at 7 36 17 PM
WhatsApp Image 2021-03-16 at 7 36 17 PM (1)

### CODE REVIEW

**Review by HimeshNayak — CHANGES_REQUESTED** [review]
Great Work @D-Ajay-Kumar!. Kindly resolve the conflicts. And implement the dropdown for course and stream.

**Comment by D-Ajay-Kumar** [comment]
I have to fetch course and stream from Firebase too?

**Comment by HimeshNayak** [comment]
> I have to fetch course and stream from Firebase too?

Yes, the issue was for college name, course and branch

**Comment by D-Ajay-Kumar** [comment]
How did these conflicts rise? Did some other PR related to this file got merged recently? I see a lot of stupid changes that make absolutely no sense like missing parenthesis, semi-colons etc.

**Comment by HimeshNayak** [comment]
> How did these conflicts rise? Did some other PR related to this file got merged recently? I see a lot of stupid changes that make absolutely no sense like missing parenthesis, semi-colons etc.

I can see conflict in only file and that quite reasonable. Are you facing any problem?

**Comment by D-Ajay-Kumar** [comment]
> I can see conflict in only file and thats quite reasonable. Are you facing any problem?

When I pushed the changes yesterday there were no parenthesis or square brackets or semi-colons missing but now there are. How did this happen? How does this usually happen in any open source project that when you push changes it's fine but after some time conflicts pop up, conflicts like missing parenthesis which aren't actually conflicts between code but errors?

**Comment by D-Ajay-Kumar** [comment]
Hahahah I've been trying to solve the conflicts but there just are so many parenthesis missing it's getting difficult to solve error.

**Comment by D-Ajay-Kumar** [comment]
Found the issue, somehow someone removed a sizedbox, a parenthesis and a square bracket in the code. Guessing removing the sizedbox wasn't a mistake since it got merged by one of the maintainers, I have resolved the error due to the missing parenthesis and square bracket.

**Review by D-Ajay-Kumar — COMMENTED** [review]
If the UI fails to match what it earlier was then that probably would be because a sizedbox has been removed by someone.

**Comment by D-Ajay-Kumar** [comment]
I might need a lil assistance here. My forked repo is 2 commits behind and there also seems to be some changes in the file this PR is about. Now that I need to make more changes to this file, should I first do

git pull upstream master

to update my local repo and then start working?

**Comment by HimeshNayak** [comment]
> I might need a lil assistance here. My forked repo is 2 commits behind and there also seems to be some changes in the file this PR is about. Now that I need to make more changes to this file, should I first do
> 
> git pull upstream master
> 
> to update my local repo and then start working?

To even your repo with the master repo
```
git remote update
git rebase upstream/master
git push 
```

**Comment by D-Ajay-Kumar** [comment]
> To even your repo with the master repo
> 
> ```
> git remote update
> git rebase upstream/master
> git push 
> ```
> 
> Also, lets have a discussion with Samarpan and figure out this issue

Won't that remove all the changes that I've made on my local repo that haven't gotten merged with the upstream master yet?

**Comment by D-Ajay-Kumar** [comment]
Or maybe merge these changes on the college dropdown because this is absolutely final and don't offer any points for this issue to me. Let's discuss over converting the remaining fields to dropdowns too and then open another issue with the new ideas.

**Review by HimeshNayak — CHANGES_REQUESTED** [review]
@D-Ajay-Kumar we'll merge this PR for college dropdown only.
But make the necessary changes first.

**Comment by D-Ajay-Kumar** [comment]
The fields are repeating?

**Comment by D-Ajay-Kumar** [comment]
Not repeating anymore

**Review by HimeshNayak — APPROVED** [review]
College dropdown has been added. The rest of the fields are also to be made dropdpwns.
For now, @avinashkranjan you can merge this PR.

**Comment by D-Ajay-Kumar** [comment]
Can you also create an issue to discuss further ideas with @SamarpanCoder2002 and me?

**Comment by SamarpanCoder2002** [comment]
> Can you also create an issue to discuss further ideas with @SamarpanCoder2002 and me?

Yah....Required a strong discussion here @D-Ajay-Kumar @HimeshNayak ...... Waiting for the reponse @HimeshNayak

**Comment by HimeshNayak** [comment]
> > Can you also create an issue to discuss further ideas with @SamarpanCoder2002 and me?
> 
> Yah....Required a strong discussion here @D-Ajay-Kumar @HimeshNayak ...... Waiting for the reponse @HimeshNayak

Lets continue on discord.

**Comment by SamarpanCoder2002** [comment]
> > > Can you also create an issue to discuss further ideas with @SamarpanCoder2002 and me?
> > 
> > 
> > Yah....Required a strong discussion here @D-Ajay-Kumar @HimeshNayak ...... Waiting for the reponse @HimeshNayak
> 
> Lets continue on discord.

ok

**Comment by D-Ajay-Kumar** [comment]
> Lets continue on discord.

Can't send more than 3 texts in 900 seconds

**Comment by HimeshNayak** [comment]
> > Lets continue on discord.
> 
> Can't send more than 3 texts in 900 seconds

we'll use the voice channel. Please check the text channel.

**Comment by SamarpanCoder2002** [comment]
> > > Lets continue on discord.
> > 
> > 
> > Can't send more than 3 texts in 900 seconds
> 
> we'll use the voice channel. Please check the text channel.

Ok Sure

**Review by avinashkranjan — APPROVED** [review]
LGTM

**Pull request merged**
