### PR TITLE
Figma design in light mode

### LINKED ISSUE #191: Light mode figma design
**Is your feature request related to a problem? Please describe.**
As the app is in dark mode I want that if it can be in light mode it will be more better for user expertise.

**Describe the solution you'd like**
To accommodate this as a designer I  can design a light mode design for the app with some different features so user gets app attractive in both modes

**Describe alternatives you've considered**

**Additional context**
I request you to please assign me the project.

### PR DESCRIPTION
**Pull request by Ks103**
# Description

I have designed the figma light mode version of this app. In that all my designs and url are in Figma design (light) folder in gh-page branch.

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Friday/blob/master/CONTRIBUTING.md)?

-  Yes

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by avinashkranjan** [comment]
@Ks103 Push the changes on gh-branch

**Comment by Ks103** [comment]
Sorry sir but I don't know who to do that , could you please guide me as all the things I have done.

**Comment by avinashkranjan** [comment]
Follow this guide https://stackoverflow.com/questions/13897717/push-commits-to-another-branch @Ks103

**Comment by Ks103** [comment]
I got it what you were saying opening new pr. sorry for the inconvenience

**Comment by Ks103** [comment]
please check issue #208

**Pull request closed without merging**
